### ISSUE TITLE
Empty dates will leave un-replaced placeholders in template

### ISSUE THREAD

**Issue by janmechtel** [tomnitschke/gristwidgets#2]
First of all, I'm super glad that this exists, saved me a ton of work.

One problem I faced was that empty dates, get mapped to {MyDate:null} which will leave the {MyDate} placeholder in the template.

I "fixed it" by adding, happy to submit a PR.

def create_placeholder_mapping(
...
      if val is None:
        val = ""
        
...

**Comment by tomnitschke** [comment]
Hey, yeah obviously this simple check was just missing, so that's a good catch, thanks. I fixed it [(see here)](https://github.com/tomnitschke/gristwidgets/commit/0a16c580e29ad3d841bdb245c719d05dd565a955), at least I hope so. Don't have time to test right now, so please let me know how it goes.
